-- AlterEnum: Add DELETE_PENDING and DELETE_FAILED to MediaAssetStatus
ALTER TYPE "MediaAssetStatus" ADD VALUE 'DELETE_PENDING';
ALTER TYPE "MediaAssetStatus" ADD VALUE 'DELETE_FAILED';

-- AlterEnum: Add MODULE_DELETED and ASSET_BULK_DELETED to AuditAction
ALTER TYPE "AuditAction" ADD VALUE 'MODULE_DELETED';
ALTER TYPE "AuditAction" ADD VALUE 'ASSET_BULK_DELETED';
